all:
  children:
    webservers:
      children:
        webservers_us:
          hosts:
            webserver1:
              hosts:
                server1_us.com:
                  ansible_host: 192.168.1.9
                  ansible_port: 22
                  ansible_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
                  ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
                  ansible_ssh_pass: root
                server2_us.com:
                  ansible_host: 192.168.1.10
                  ansible_port: 22
                  ansible_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
                  ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
                  ansible_ssh_pass: root
            webserver2:
              hosts:
                server1_eu.com:
                  ansible_host: 192.168.1.11
                  ansible_port: 22
                  ansible_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
                  ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
                  ansible_ssh_pass: root
                server2_eu.com:
                  ansible_host: 192.168.1.12
                  ansible_port: 22
                  ansible_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
                  ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
                  ansible_ssh_pass: root
